services:
  app:
    build:
      target: prod
    environment:
      NODE_ENV: production
      HOME_URL: ${PROD_URL}
      VITE_HOME_URL: ${PROD_URL}
    networks:
      - app-net

  nginx:
    build:
      context: ..
      dockerfile: containers/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - app
    networks:
      - app-net
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template:ro

  adminer:
    image: adminer:standalone
    container_name: adminer
    restart: unless-stopped
    ports:
      - "127.0.0.1:54245:8080"
    networks:
      - adminer

  db:
    networks:
      - adminer

networks:
  app-net:
    driver: bridge
  adminer:
    driver: bridge
