export enum EmailContents {
  DEL_OBJ = 'Account Deletion',
  DEL_MSG = 'The account associated with this email address has been deleted',
  VER_OBJ = 'Email Verification',
  VER_MSG = `<p>Please click on the link below in order to verify your email address:</p><p><a title="Card Nest Email Verification "href="VERIFY_URL">Click here to verify</a></p><p>If you did not create this request please click the link below:</p><p><a title="Cancel Request "href="CANCEL_URL">Click here to cancel</a></p>`,
  VER_SUCCESS_OBJ = 'Email Verified',
  VER_SUCCESS_MESSAGE = `<p>Your email address has been successfully verified.</p><p><a title="Card Nest Home" href="URL">Card Nest Home Page</a></p>`,
  EXP_DEL_OBJ = 'Account Deleted',
  EXP_DEL_MSG = 'The account linked to this email address has been deleted as it was not verified within the time limit.',
  EXP_MOD_OBJ = 'Email Address Change Request Cancelled',
  EXP_MOD_MSG = 'You recently requested to change your email address to EMAIL. This request has been cancelled as it was not verified with the time limit.',
  PWD_RESET_OBJ = 'Password Reset',
  PWD_RESET_MSG = `<p>Click on the link below to reset your password:</p><p><a title="Reset Password" href="RESET_URL">Click here to reset your password</a></p><p>This link expires in 30 minutes.</p>`,
  PWD_RESET_UNVERIFIED_OBJ = 'Password Reset Request',
  PWD_RESET_UNVERIFIED_MSG = `<p>You requested a password reset, but your email address has not been verified yet.</p><p>Please verify your email first by clicking the link below:</p><p><a title="Verify Email" href="VERIFY_URL">Click here to verify your email</a></p><p>If you did not create this request please click the link below:</p><p><a title="Cancel Request" href="CANCEL_URL">Click here to cancel</a></p>`,
  PWD_RESET_SUCCESS_OBJ = 'Password Reset Successful',
  PWD_RESET_SUCCESS_MSG = `<p>Your password has been successfully reset.</p><p><a title="Card Nest Home" href="URL">Card Nest Home Page</a></p>`,
}
